# Generated by Django 4.2.7 on 2023-11-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_house_pet_allowed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='pet_allowed',
            new_name='pets_allowed',
        ),
    ]
